### ISSUE TITLE
Why you need a docker ?

### ISSUE THREAD

**Issue by rabea98** [adampetrovic/docker-pyinstalive#2]
Hi,
Why do you need a docker to run pyinstalive?

**Comment by adampetrovic** [comment]
You certainly don't **NEED** docker to run pyinstalive. It's there for convenience.

The convenience is that you don't need to worry about how application should be set up (resolving dependencies, runtime arguments etc) it's handled for you in the docker image. 

Also, if you'd like to run it indefinitely, you can let Docker handle the supervision of the process without having to set up systemd or some other process supervisor.
